InternalError("Throwable(Object(Some(Object(RwLock { data: Object(java/lang/InternalError)
  backtrace=java/lang/StackTraceElement[5]
  detailMessage=String(\"Operand stack overflow\")
  cause=Object(class java/lang/InternalError)
  stackTrace=java/lang/StackTraceElement[0]
  depth=int(5)
  suppressedExceptions=Object(class java/util/Collections$EmptyList)
 })))):
stdout: === Module Path and Resources Tests ===
--- Test: Module Path ---
Module path property: null
Upgrade module path: null
Boot module path: null
Current working directory: /Users/brianheineman/development/ristretto/ristretto_vm
--- Test: Resource Access ---
Current module: unnamed module @10703920
Class loader: jdk.internal.loader.BuiltinClassLoader@10702150
Resource /Test.java found: true
Relative Test.java found: true
Error testing resource access: illegal lookupClass: class java.lang.invoke.LambdaMetafactory
--- Test: Class Loading ---
